name: Deploy

on:
  release:
    types: [published]

jobs:

  deploy-project:

    name: Deploy
    runs-on: ubuntu-latest

    env:
      S3_BUCKET: 'poc-devops-frontend'
      CDN_DISTRIBUTION_ID: 'E2SZRISXTY5W0O'
      AWS_REGION: 'eu-west-3'

    steps:

      - name: Find latest release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          view_top: 1

      - name: Print latest release metadata
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
