name: Trigger
on:
  release:
    types: [edited]
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release asset
        id: download-release-asset
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "*.zip"
      - name: Print results
        run: |
          ls -al
          echo "tag ${{ steps.download-release-asset.outputs.tag_name }}"
